# filename: config.ini
# coding: utf-8
[Base]
APP: Joyrun
debug: false

[Joyrun]
# 每次修改配置之后必须保存
StudentID: 19164090496
Password: 123456
suffix: 

record_type: xicao
record_number: 1

#distance: 距离，单位km
#pace: 每公里多少分钟
#stride_frequncy: 步幅


distance: 3.5
pace: 4
stride_frequncy: 180